FROM node:20-alpine AS build
WORKDIR /app
COPY apps/dashboard/package.json /app/package.json
RUN npm install
COPY apps/dashboard /app
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
